### ISSUE TITLE
Error when running anything

### ISSUE THREAD

**Issue by Unknown-User2** [photon-niko/shapes#1]
When i try to run anything i get the error 
```
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/mnt/suchDrives/codeThingys/shapes/shapes/__main__.py", line 2, in <module>
    from shapes.interpreter import Interpreter
  File "/mnt/suchDrives/codeThingys/shapes/shapes/interpreter.py", line 69
    match self.current.get_shape_type():
          ^
SyntaxError: invalid syntax
```

**Comment by photon-niko** [comment]
that means you are using python 3.9 or lower. use [this 3.9 version of the module](https://github.com/photon-niko/shapes/tree/main/shapes39) to use it with python 3.9

**Comment by photon-niko** [comment]
Sorry for the confusion. It is now clarified in the readme :)
